---
abstract: 'keep those pesky gophers out of your dists!'
author:
  - 'Randy Stauner <rwstauner@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102343, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-GopherRepellent
no_index:
  directory:
    - corpus
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Dist::Zilla::PluginBundle::GopherRepellent:
    file: lib/Dist/Zilla/PluginBundle/GopherRepellent.pm
    version: 0.004001
  Pod::Weaver::PluginBundle::GopherRepellent:
    file: lib/Pod/Weaver/PluginBundle/GopherRepellent.pm
    version: 0.004001
requires:
  Dist::Zilla: 2.100922
  Dist::Zilla::Plugin::CompileTests: 1.100740
  Dist::Zilla::Plugin::Git::DescribeVersion: 0.006
  Dist::Zilla::Plugin::GitFmtChanges: 0.003
  Dist::Zilla::Plugin::GithubMeta: 0.10
  Dist::Zilla::Plugin::MetaNoIndex: 1.101130
  Dist::Zilla::Plugin::MetaProvides::Package: 1.11044404
  Dist::Zilla::Plugin::MinimumPerl: 0.02
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PortabilityTests: 0
  Dist::Zilla::Plugin::Repository: 0.16
  Dist::Zilla::Plugin::TaskWeaver: 0.101620
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  Moose::Autobox: 0
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::PluginBundle::Default: 0
  Pod::Weaver::Section::Support: 1.000
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-GopherRepellent
  homepage: http://github.com/magnificent-tears/dist-zilla-pluginbundle-gopherrepellent/tree
  repository: git://github.com/magnificent-tears/dist-zilla-pluginbundle-gopherrepellent.git
version: 0.004001
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::DescribeVersion
      name: '@GopherRepellent/Git::DescribeVersion'
      version: 0.006012
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@GopherRepellent/GatherDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@GopherRepellent/PruneCruft'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@GopherRepellent/ManifestSkip'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@GopherRepellent/PkgVersion'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@GopherRepellent/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::License
      name: '@GopherRepellent/License'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@GopherRepellent/Readme'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: '@GopherRepellent/GitFmtChanges'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@GopherRepellent/Bugtracker'
      version: 1.102670
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@GopherRepellent/Repository'
      version: 0.16
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@GopherRepellent/GithubMeta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@GopherRepellent/AutoPrereqs'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@GopherRepellent/MetaNoIndex'
      version: 1.101550
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@GopherRepellent/MetaProvides::Package'
      version: 1.12044908
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@GopherRepellent/MinimumPerl'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@GopherRepellent/MetaConfig'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@GopherRepellent/MetaYAML'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@GopherRepellent/MetaJSON'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@GopherRepellent/TestMoreWithSubtests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@GopherRepellent/ExtraTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@GopherRepellent/ExecDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@GopherRepellent/ShareDir'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@GopherRepellent/MakeMaker'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@GopherRepellent/CompileTests'
      version: 1.103030
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@GopherRepellent/MetaTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@GopherRepellent/PodSyntaxTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@GopherRepellent/PodCoverageTests'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@GopherRepellent/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@GopherRepellent/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@GopherRepellent/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@GopherRepellent/Manifest'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@GopherRepellent/TestRelease'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@GopherRepellent/ConfirmRelease'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@GopherRepellent/UploadToCPAN'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102343
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102343
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102343
