---
abstract: 'keep those pesky gophers out of your dists!'
author:
  - 'Randy Stauner <rwstauner@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-GopherRepellent
no_index:
  directory:
    - corpus
    - examples
    - inc
    - share
    - t
    - xt
provides:
  Dist::Zilla::PluginBundle::GopherRepellent:
    file: lib/Dist/Zilla/PluginBundle/GopherRepellent.pm
    version: 1.002
  Pod::Weaver::PluginBundle::GopherRepellent:
    file: lib/Pod/Weaver/PluginBundle/GopherRepellent.pm
    version: 1.002
recommends:
  Dist::Zilla::Plugin::PodLinkTests: 1.003
requires:
  Dist::Zilla: 4.102345
  Dist::Zilla::Plugin::Authority: 1.001
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::CPANChangesTests: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0.003
  Dist::Zilla::Plugin::CompileTests: 1.100740
  Dist::Zilla::Plugin::DualBuilders: 1.001
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::GithubMeta: 0.10
  Dist::Zilla::Plugin::KwaliteeTests: 0
  Dist::Zilla::Plugin::MetaNoIndex: 1.101130
  Dist::Zilla::Plugin::MetaProvides::Package: 1.11044404
  Dist::Zilla::Plugin::MinimumPerl: 0.02
  Dist::Zilla::Plugin::MinimumVersionTests: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSpellingTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PortabilityTests: 0
  Dist::Zilla::Plugin::Prepender: 1.100960
  Dist::Zilla::Plugin::ReportVersions::Tiny: 1.01
  Dist::Zilla::Plugin::Repository: 0.16
  Dist::Zilla::Plugin::TaskWeaver: 0.101620
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Dist::Zilla::Stash::PodWeaver: 1.001000
  Moose: 0
  Pod::Elemental: 0.102360
  Pod::Elemental::Transformer::List: 0
  Pod::Weaver: 3.101632
  Pod::Weaver::Config::Assembler: 0
  Pod::Weaver::Plugin::StopWords: 1.001005
  Pod::Weaver::Plugin::Transformer: 0
  Pod::Weaver::Plugin::WikiDoc: 0
  Pod::Weaver::PluginBundle::Default: 0
  Pod::Weaver::Section::Support: 1.001
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-GopherRepellent
  homepage: http://github.com/magnificent-tears/Dist-Zilla-PluginBundle-GopherRepellent/tree
  repository: git://github.com/magnificent-tears/Dist-Zilla-PluginBundle-GopherRepellent.git
version: 1.002
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@GopherRepellent/Git::NextVersion'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@GopherRepellent/GatherDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@GopherRepellent/PruneCruft'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@GopherRepellent/ManifestSkip'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@GopherRepellent/Authority'
      version: 1.004
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@GopherRepellent/NextRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@GopherRepellent/PkgVersion'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@GopherRepellent/Prepender'
      version: 1.103470
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@GopherRepellent/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::License
      name: '@GopherRepellent/License'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@GopherRepellent/Readme'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@GopherRepellent/Bugtracker'
      version: 1.102670
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@GopherRepellent/Repository'
      version: 0.17
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@GopherRepellent/GithubMeta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@GopherRepellent/AutoPrereqs'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@GopherRepellent/MetaNoIndex'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@GopherRepellent/MetaProvides::Package'
      version: 1.12060501
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@GopherRepellent/MinimumPerl'
      version: 1.002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@GopherRepellent/MetaConfig'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@GopherRepellent/MetaYAML'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@GopherRepellent/MetaJSON'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@GopherRepellent/TestMoreWithSubtests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@GopherRepellent/ExtraTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@GopherRepellent/ExecDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@GopherRepellent/ShareDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@GopherRepellent/MakeMaker'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@GopherRepellent/ModuleBuild'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: '@GopherRepellent/DualBuilders'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@GopherRepellent/CompileTests'
      version: 1.110930
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@GopherRepellent/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::CPANChangesTests
      name: '@GopherRepellent/CPANChangesTests'
      version: 1.001
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@GopherRepellent/MetaTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@GopherRepellent/PodSyntaxTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@GopherRepellent/PodCoverageTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodSpellingTests
      name: '@GopherRepellent/PodSpellingTests'
      version: 1.103491
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@GopherRepellent/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@GopherRepellent/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@GopherRepellent/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@GopherRepellent/Manifest'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@GopherRepellent/CheckChangesHasContent'
      version: 0.003
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@GopherRepellent/TestRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@GopherRepellent/ConfirmRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@GopherRepellent/UploadToCPAN'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: RuntimeRequires
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200004
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200004
x_authority: cpan:RWSTAUNER
